create the basic components of the site
nilienta/react-burger pull request #1
Opened 2022-09-30 19:19 UTC by nilienta

2022-09-30 19:50 UTC, ArslanDev666 requested changes
## Code review

### Работа отклоняется от проверки, т.к. проект не билдится, и запускается с ошибками.

2022-10-02 13:54 UTC, nilienta commented
Ошибки исправлены, сейчас должен билдиться

2022-10-02 19:46 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
> +});
**Можно лучше:** во многих компонентах дублируется описание PropTypes ингредиента
Лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src) и переиспользовать описание пропсов ингрединта, а не дублировать

2022-10-02 19:56 UTC, ArslanDev666 commented on src/components/ingredients-list/ingredients-list.js
> +    }
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

2022-10-02 20:12 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
> +        key="1212f3f412f3f23g3"
**Надо исправить :** Здесь не требуется использоватьт key.
https://ru.react.js.org/docs/lists-and-keys.html

2022-10-02 20:14 UTC, ArslanDev666 commented on src/components/constructor-element-wrap/constructor-element-wrap.js
> +  }
**Надо исправить:** Лучше написать в самом jsx условие.
Так мы повысим читабельность кода, и не будет лишних проверок.
```js
 {props.type &&
    <div className={styles.icon}>
      <img src={icon} alt="" width="14" height="19" />
    </div>
  }
```

2022-10-02 20:15 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодцы!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- В директории `components` должен быть компонент App. Компонент `App`, как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app.

- Для многих компонентов не описаны propTypes.

- Используйте деструктуризацию у пропсов, чтобы было понятно, какие пропсы передаются в компонент.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-10-03 15:19 UTC, nilienta commented on src/components/total-price/total-price.js
> +  return (
rfefer

2022-10-10 04:06 UTC, merged