Sprint 1/step 2
nilienta/react-burger pull request #2
Opened 2022-10-05 18:30 UTC by nilienta

creating Modal, ModalOverlay, IngredientDetails, OrderDetails components. typing is done and API is connected

2022-10-06 08:18 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app. (App.test.tsx)

- Неправильно описаны propTypes для ингредиента, там намного больше параметров.

- В некоторых местах в propTypes описаны не все пропсы.

- Поправить логику закрытия по `Escape`, в компоненте Modal.

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-06 08:18 UTC, ArslanMustafin commented on src/components/App/App.tsx
> +		}
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте.

**Можно лучше**
вызывать скрытие индикатора загрузки слудеует в блоке `finally`, а не дублировать в `then` и `catch`
[https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

2022-10-06 08:18 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredient/ingredient.js
> +      )}
**Можно лучше:** Лучше вынести модальное окно в burgerIngredients, а не вставлять в каждый ингредиент. Так мы сократим количество затрачиваемой памяти.

2022-10-06 08:18 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredients-list/ingredients-list.js
> +  const sauces = data.filter((item) => item.type === 'sauce');
**Можно лучше**
используйте useMemo, что бы фильтрация ингредиентов не вызывалась при каждом ренедере, например:
```
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
.....
```

2022-10-06 08:18 UTC, ArslanMustafin commented on src/components/burger-ingredients/tab-wrap/tab-wrap.js
> +    <div style={{ display: 'flex' }} className="mt-5 mb-10">
**Надо исправить:** Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2022-10-06 08:18 UTC, ArslanMustafin commented on src/components/modal/modal-header/modal-header.js
> +export default ModalHeader;
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-06 08:18 UTC, ArslanMustafin commented on src/components/modal/modalOverlay/modal-overlay.js
> +export default ModalOverlay;
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/modal/modalOverlay/modal-overlay.js
> +const ModalOverlay = ({ onClose, children }) => {
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер`

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/modal/modal.js
> +  );
**Надо исправить:** Навешение обработчиков событий лучше надо делать в useEffect. Вот хорошое обсуждение, https://stackoverflow.com/questions/55565444/how-to-register-event-with-useeffect-hooks.

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/app-header/navigation-link/navigation-link.js
> +NavigationLink.propTypes = {
**Надо исправить:** Не описан propTypes для children

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/burger-constructor/constructor-element-wrap/constructor-element-wrap.js
> +export default ConstructorElementWrap;
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient/ingredient.js
> +Ingredient.propTypes = {
**Надо испарвить** Не описан propTypes - item

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient-details/ingredient-details.js
> +export default IngredientDetails;
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient-details/ingredient-details.js
> +const Composition = ({ elements }) => {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient-details/ingredient-details.js
> +const Element = ({ name, count }) => {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredients-list/ingredients-list.js
> +  const Ingredients = ({ thread }) => (
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredients-list/ingredients-list.js
> +const IngredientsList = ({ data }) => {
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2022-10-06 08:18 UTC, ArslanDev666 commented on src/components/modal/modal.js
> +Modal.propTypes = {
**Надо исправить :** Не описаны propTypes для children

2022-10-06 08:18 UTC, ArslanMustafin commented on src/components/burger-ingredients/tab-wrap/tab-wrap.js
> +      <Tab value="one" active={current === 'one'} onClick={setCurrent}>
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (Лучший вариант, это использовать ref'ы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2022-10-07 11:31 UTC, nilienta commented on src/components/App/App.tsx
> +		}
Пока не могу нормально импортировать функцию, тайпскрипт сильно ругается, а мы пока не дошли до блока по работе с ним.  В дальнейшем воспользуюсь вашими рекомендациями

2022-10-08 21:18 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

### **Но есть несколько новых замечаний, которые нужно исправить:**

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app. (setupTests.ts)

- По поводу работы с запросами, `это не обязательно`, но чтобы решить проблему с ts (typescript), можно просто поменять расширения файла на `.jsx` и тогда всё спокойно вынесется.

- Поправить логику закрытия по `Escape`, в компоненте Modal.

### **Сделает код лучше:**

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-08 21:18 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.js
> +  });
**Можно лучше:** Тут можно использовать просто `useState`, без объекта.
```js 
  const [visibleModal, setVisibleModal] = React.useState(false);
  ```

2022-10-08 21:18 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredients-list/ingredients-list.js
> +  const sauces = getOneType('sauce');
**Можно лучше:** Что-то вы тут намудрили), в таком случае useMemo, тут только память будет забирать, а пользы от него не будет. Можно написать вот так: 
```js 
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);
```
либо можно обернуть всё в 1 useMemo, и возвращать объект (Этот вариант лучше всего).

```js
  const { buns, mains, sauces } = useMemo(
    () => ({
      buns: data.filter((item) => item.type === 'bun'),
      mains: data.filter((item) => item.type === 'main'),
      sauces: data.filter((item) => item.type === 'sauce'),
    }),
    [data]
  );
```

2022-10-08 21:18 UTC, ArslanMustafin commented on src/components/burger-ingredients/ingredients-list/ingredients-list.js
> +  const Ingredients = ({ thread, open, srcClick }) => {
**Надо исправить:** компонент лучше вынести за пределы родительского компонента, в идеале, создать отдельную папочку под него.

2022-10-08 21:18 UTC, ArslanDev666 commented on src/components/burger-ingredients/tab-wrap/tab-wrap.js
> +      <Tab value="one" active={current === 'one'} onClick={() => setTab('one')}>
**Можно лучше:** onClick у данного компонента, по умолчанию передает туда value. поэтому можно написать просто setTab, без параметров. А  еще лучше переименовать эту функцию в handleClickTab.

```js
<Tab {...} onClick={setTab}>
```

2022-10-08 21:18 UTC, ArslanDev666 commented on src/components/modal/modal.js
> +    );
**Надо исправить**
Обработчик закрытия попапа должен добавляться при открытии попапа и удаляться при закрытии. Сейчас обработчик не будет удаляться при закрытии попапа т.к. из хука useEffect нужно возвращать колбэк отписки. Должно быть примерно так:

```
   useEffect(() => {
      const handleESCclose = () => {............} //обработчик события
      document.addEventListener("keydown", handleESCclose); //навешиваем обработчик
	  
	  //возвращаем колбэк отписки, который  будет вызван при размонтировании компонента
      return () => document.removeEventListener("keydown", handleESCclose)                                                                                               
   }, [onClose])
```

2022-10-08 21:18 UTC, ArslanDev666 commented on src/components/modal/modalOverlay/modal-overlay.js
> +  };
**Можно лучше:** Тут можно не проверять, достаточно просто вызвать onClose(), или что еще лучше, сразу передать onClose, в качестве обработчика событий. Т.к это подложка, и от неё никак не сработает, всплытие событий на соседний попап.

2022-10-08 21:18 UTC, ArslanDev666 commented on src/components/modal/modal.js
> +`;
**Можно лучше:** такую анимацию можно самим написать, не уверен что стоит тащить 2 дополнительные библиотеки, ради 1 анимации, да и смешивать разные виды стилей(css-modules, styled-components), это плохо.

2022-10-08 21:42 UTC, nilienta commented on src/components/modal/modal.js
> +    );
а разве 2 аргумент `{ once: true }` не говорит обработчику больше "не слушать" после перового срабатывания, есть ли между этим методом и вашим какая-то разницы?

2022-10-08 22:28 UTC, ArslanDev666 commented on src/components/modal/modal.js
> +    );
Да есть разница, слушатель события не удаляется, ведь у нас есть еще несколько способ как мы можем закрыть попап. Можете сами проверить, сделав log в обработчике событий. После этого закрыть окно, любым способом(кроме нажатия на клавишу `Esc`). А потом нажать на клавишу `Еsc`. и у вас в консоли должен быть ваш log.

![image](https://user-images.githubusercontent.com/70164458/194729862-f769dc9c-729f-45ae-8ff7-55e48712e4d1.png)

2022-10-09 22:29 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодцы!🔥🔥🔥 Работа принята.**

### **Сделает код лучше:**

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде. Если возникнут какие-либо вопросы, то буду рад на них ответить_**

2022-10-09 22:29 UTC, ArslanDev666 commented on src/components/modal/modal.js
> +  }, []);
**Можно лучше:** Лучше занести функцию в сам useEffect. Эффект будет 1 и тот же, но мы будем потреблять меньше памяти.

2022-10-10 04:05 UTC, merged